# Generated by Django 4.0.4 on 2022-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=25)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=25)),
                ('stream', models.CharField(max_length=25)),
                ('rollno', models.CharField(max_length=25)),
                ('profile_pic', models.FileField(upload_to='images/')),
                ('dob', models.DateField(max_length=25)),
                ('user_type', models.BooleanField(default=False)),
            ],
        ),
    ]
