# Generated by Django 4.0.4 on 2022-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='section',
            field=models.CharField(choices=[('section-A', 'A'), ('section-B', 'B'), ('section-C', 'C')], max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='standard',
            field=models.CharField(choices=[('1st', '1'), ('2nd', '2'), ('3rd', '3'), ('4th', '4'), ('5th', '5'), ('6th', '6'), ('7th', '7'), ('8th', '8'), ('9th', '9'), ('10th', '10')], max_length=25),
        ),
    ]
