# Generated by Django 4.0.4 on 2022-08-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_register_section_alter_register_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('standard', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], max_length=25)),
                ('section', models.CharField(choices=[('section-A', 'section-A'), ('section-B', 'section-B'), ('section-C', 'section-C')], max_length=25)),
                ('stream', models.CharField(max_length=25)),
                ('rollno', models.CharField(max_length=25)),
                ('profile_pic', models.FileField(upload_to='images/')),
                ('dob', models.DateField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
