# Generated by Django 4.0.4 on 2022-08-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_registerstudent_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('classes', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('profile_pic', models.FileField(upload_to='images/')),
                ('dob', models.DateField(max_length=25)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
